[ "$(uname -s | tr '[:upper:]' '[:lower:]')" = 'linux' ] && alias ls='ls --color=auto'
alias ll='ls -lihF'
alias la='ls -A'
alias l='ll -A'

alias sudo='sudo '
alias grep='grep -n --color=auto'
alias j='jobs'
alias ne='emacs'
alias df='df -h'
alias weechat='TERM=screen-256color weechat'
alias lock='xscreensaver-command --lock'
hash htop 2>/dev/null && alias top='TERM=screen-256color htop'
