[ "$(uname -s | tr '[:upper:]' '[:lower:]')" = 'linux' ] && alias ls='ls --color=auto'
alias ll='ls -lihF'
alias la='ls -A'
alias l='ll -A'

alias t='tree'
alias sudo='sudo '
alias grep='grep -n --color=auto'
alias j='jobs'
alias df='df -h'
alias du='du -ch'
hash htop 2>/dev/null && alias top='htop'
